apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: postgres-dev
build:
  artifacts:
    - image: postgres-dev
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
portForward:
  - resourceType: deployment
    resourceName: postgres-dev
    port: 5432
    localPort: 5432
